### ISSUE TITLE
Api not working

### ISSUE THREAD

**Issue by Kloppis** [rjt-rockx/mee6-levels-api#3]
Hey, i'm using the api in my discord bot to get the levels from mee6 and set rolls.
the bot is working fine so far to set rolls aso.
as soon as i import the api the bot will not start anymore giving the following error:
`internal/util.js:214
    throw new errors.TypeError('ERR_INVALID_ARG_TYPE', 'original', 'function');
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "original" argument must be of type function
    at Object.promisify (internal/util.js:214:11)
    at Object.<anonymous> (/home/nicobot/node_modules/got/dist/source/get-response.js:8:25)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nicobot/node_modules/got/dist/source/request-as-event-emitter.js:13:24)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/nicobot/node_modules/got/dist/source/as-promise.js:9:36)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
`
Is there anything i am missing?

**Comment by rjt-rockx** [comment]
Seems to be working fine at the moment.
